version: '3'
services:
  web1:
    build: .
    container_name: web_green
    ports:
      - "8081:80"
    volumes:
      - ./index1.html:/usr/share/nginx/html/index.html

  web2:
    build: .
    container_name: web_orange
    ports:
      - "8082:80"
    volumes:
      - ./index2.html:/usr/share/nginx/html/index.html

  web3:
    build: .
    container_name: web_blue
    ports:
      - "8083:80"
    volumes:
      - ./index3.html:/usr/share/nginx/html/index.html
