version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1
    ports:
      - "2000:2000"
    volumes:
      - ./index_green.html:/usr/share/nginx/html/index.html

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2
    ports:
      - "3000:2000"
    volumes:
      - ./index_orange.html:/usr/share/nginx/html/index_orange.html

  web3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3
    ports:
      - "4000:2000"
    volumes:
      - ./index_darkgreen.html:/usr/share/nginx/html/index_darkgreen.html
